- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-scenario002
      - puppet-openstack-litmus-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-swift-tripleo-standalone
    gate:
      jobs:
        - puppet-swift-tripleo-standalone

- job:
    name: puppet-swift-tripleo-standalone
    parent: tripleo-puppet-ci-centos-9-standalone
    description: |
      TripleO standalone Job running Object Storage specific Tempest tests.
    vars:
      build_container_images: true
      featureset_override:
        run_tempest: false
        tempest_test_whitelist:
          - 'tempest.api.object_storage.test_object_services.ObjectTest'
        use_os_tempest: true
