name    'puppetlabs-swift'
version '2.0.0'
source  'https://github.com/stackforge/puppet-swift'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Swift Module'
description 'Puppet module to install and configure the OpenStack Swift object storage service'
project_page 'https://launchpad.net/puppet-openstack'

## Add dependencies, if any:
dependency 'puppetlabs/keystone', '>= 2.0.0'
dependency 'puppetlabs/mysql','>= 0.6.1'
dependency 'puppetlabs/rsync', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 2.3.0'
dependency 'puppetlabs/xinetd', '>= 1.0.1'
dependency 'ripienaar/concat', '>= 0.1.0'
dependency 'saz/memcached', '>= 2.0.2'
dependency 'saz/ssh', '>= 1.0.2'
